#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-websockets
Version  : 10.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/b4/7b/0960d02701f783bb052ec69ea32789d878d2cce05a03950adbd75f164758/websockets-10.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b4/7b/0960d02701f783bb052ec69ea32789d878d2cce05a03950adbd75f164758/websockets-10.2.tar.gz
Summary  : An implementation of the WebSocket Protocol (RFC 6455 & 7692)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-websockets-license = %{version}-%{release}
Requires: pypi-websockets-python = %{version}-%{release}
Requires: pypi-websockets-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. image:: logo/horizontal.svg
:width: 480px
:alt: websockets
|licence| |version| |pyversions| |wheel| |tests| |docs|

%package license
Summary: license components for the pypi-websockets package.
Group: Default

%description license
license components for the pypi-websockets package.


%package python
Summary: python components for the pypi-websockets package.
Group: Default
Requires: pypi-websockets-python3 = %{version}-%{release}

%description python
python components for the pypi-websockets package.


%package python3
Summary: python3 components for the pypi-websockets package.
Group: Default
Requires: python3-core
Provides: pypi(websockets)

%description python3
python3 components for the pypi-websockets package.


%prep
%setup -q -n websockets-10.2
cd %{_builddir}/websockets-10.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649814467
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-websockets
cp %{_builddir}/websockets-10.2/LICENSE %{buildroot}/usr/share/package-licenses/pypi-websockets/b61db1cb007caaf9118a9bf274e9a07ed1875d2c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-websockets/b61db1cb007caaf9118a9bf274e9a07ed1875d2c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
